
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 07 23:56:33 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 15;
  public static final int CONST = 5;
  public static final int CHAR = 13;
  public static final int CASE = 45;
  public static final int NOT_EQUAL = 30;
  public static final int LPAREN = 9;
  public static final int GREATER = 31;
  public static final int SEMI = 6;
  public static final int CONTINUE = 21;
  public static final int MINUS = 36;
  public static final int LESS = 33;
  public static final int RPAREN = 10;
  public static final int AND = 27;
  public static final int OR = 26;
  public static final int QMARK = 46;
  public static final int BOOL = 12;
  public static final int COMMA = 7;
  public static final int CLASS = 8;
  public static final int INC = 24;
  public static final int DIV = 38;
  public static final int LESS_EQUAL = 34;
  public static final int PLUS = 35;
  public static final int TWODOT = 47;
  public static final int ASSIGN = 40;
  public static final int IF = 19;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RBRACKET = 16;
  public static final int EQUAL = 29;
  public static final int GREATER_EQUAL = 32;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int MOD = 39;
  public static final int NUMBER = 11;
  public static final int BREAK = 20;
  public static final int IDENT = 14;
  public static final int VOID = 41;
  public static final int SWITCH = 44;
  public static final int ELSE = 48;
  public static final int LBRACE = 3;
  public static final int READ = 23;
  public static final int WHILE = 43;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 25;
  public static final int DO = 42;
  public static final int PRINT = 17;
}

